name: build64

on: workflow_dispatch

jobs:
  GenerateWinStaticBinaries:
    runs-on: windows-2022

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Install Python 3.7 version
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: setup msvc
      uses: ilammy/msvc-dev-cmd@v1.13.0
      with:
        arch: 'amd64'
    - name: Compile static Qt version
      run: |
        # Clone Qt6 repo
        cd ..
        git clone https://code.qt.io/qt/qt5.git -b 6.6.1
        cd qt5
        perl init-repository -f --module-subset=qt5compat,qt3d,qtbase,qtcharts,qtdeclarative,qtimageformats,qtlanguageserver,qtmqtt,qtmultimedia,qtnetworkauth,qtquick3d,qtquicktimeline,qtserialbus,qtserialport,qtshadertools,qtsvg,qtwebchannel,qtwebengine,qtwebsockets,qtwebview
        # Create shadow build folder
        cd ..
        mkdir qt6_shadow
        cd qt6_shadow
        # Setup the compiler
        # Configure Qt6
        ..\qt5\configure.bat -release -static -static-runtime -no-pch -optimize-size -platform win32-msvc -prefix "..\Qt6_binaries" -no-feature-accessibility -confirm-license -- -DFEATURE_cxx20=ON
        cmake --build . --parallel 4
        cmake --install .
    - uses: actions/upload-artifact@v4
      with:
        overwrite: true
        name: qt6_661_static_64
        path: Qt6_binaries
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: Qt6_binaries
  
